import Head from 'next/head'
import { useContext, createContext } from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '/components/Header'
import Property from '../model/nieruchomosci'
import Homeview from '@/components/Homeview'
import Content from '@/components/Content'
import mongoose from 'mongoose'
import Specialoffers from '@/components/Specialoffers'

const inter = Inter({ subsets: ['latin'] })
export const MainContext = createContext(); 

export default function Home({property}) {
  return (
    <MainContext.Provider value={{property}}>
      <Head>
        <title>Marszałek nieruchomości</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Homeview />
        <Content />
      </main>
    </MainContext.Provider>
  )
}

export async function getServerSideProps (contex) {

  console.log("Przed połączeniem")
  await mongoose.connect(process.env.MONGO_URI)
  console.log("Połączono!")

  const results = await Property.find({recomended:true})
  const properties = await JSON.parse(JSON.stringify(results))

  return {
    props:{
      property: properties,
    }
  }
}










